backend:
  name: git-gateway
  repo: tsaristbomba/blog-starter
  branch: master

media_folder: content/assets
public_folder: ../assets
locale: "en"

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Data, widget: date }
      - { name: image, label: Thumbnail Image, widget: image, required: false }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list }
      - { name: description, label: Description }
      - { name: body, label: Post, widget: markdown }
